refactor(global_entry_data): use flat_hash_map instead of F14FastMap
The F14 map in combination with range-v3 was causing strange warning
with some versions of GCC:

```
    inlined from 'static void dwarfs::writer::internal::global_entry_data::index(map_type<std::__cxx11::basic_string<char>, unsigned int>&)' at /home/mhx/git/github/dwarfs/src/writer/internal/global_entry_data.cpp:63:51:
/usr/lib/gcc/x86_64-pc-linux-gnu/13/include/g++-v13/bits/stl_iterator_base_funcs.h:162:7: error: iteration 288230376151711743 invokes undefined behavior [-Werror=aggressive-loop-optimizations]
  162 |       while (__n--)
      |       ^~~~~
```